version: "3.8"
services:
  nginx:
    restart: always
    image: nginx:1.21.4
    ports:
      - ${NGINX_PORT}:80
    volumes:
      -  ../../nginx/nginx-dev.conf:/etc/nginx/nginx.conf
      -  ../../${VOLUME_PATH}/images:/static/images
    networks:
      - ${DOCKER_NETWORK_NAME}
    depends_on:
      - api

  api:
    image: app/api-flask:dev
    build:
      context:  ../../
      dockerfile:  ../base/Dockerfile
    restart: always
    env_file:
      -  ../../${ENV_PATH}
    volumes:
      -  ../../api:/opt/app/api
      -  ../../${VOLUME_PATH}:/opt/app/volumes
    working_dir: /opt/app/api
    command: "python3 app.py"
    networks:
      - ${DOCKER_NETWORK_NAME}
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      -  ../../${VOLUME_PATH}/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRESQL_EXPOSE_PORT}:5432
    networks:
      - ${DOCKER_NETWORK_NAME}

  redis:
    image: redis:6.2.6
    restart: always
    volumes:
      -  ../../${VOLUME_PATH}/redis_data:/data
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    networks:
      - ${DOCKER_NETWORK_NAME}

volumes:
  postgres:

networks:
  app-dev:
    external: true
  app-test:
    external: true
