"""empty message

Revision ID: 84b80afa45aa
Revises: 49f50def1942
Create Date: 2021-12-22 22:58:41.911968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b80afa45aa'
down_revision = '49f50def1942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img_path', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_img_path')
    # ### end Alembic commands ###
