version: "3.8"
services:
  web:
    restart: always
    image: app/web-react-rest:dev
    env_file:
      - $PWD/../../.env.dev
    volumes:
      - $PWD/../../web/src:/opt/app/web/src
      - $PWD/../../web/public:/opt/app/web/public
    working_dir: /opt/app/web
    command: "yarn start"
    networks:
      - ${DOCKER_NETWORK_NAME}

networks:
  app-dev:
    external: true